{% set name = "multiprocess" %}
{% set version = "0.70.6.1" %}
{% set sha256 = "985d2faa28def907e303b4222b01281d2dcd3baa0fe53a4a0178ac63be62e5c6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - dill >=0.2.8.2
  run:
    - python
    - dill >=0.2.8.2

test:
  # Python imports
  imports:
    - _multiprocess
    - multiprocess
    - multiprocess.dummy

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://pypi.org/project/multiprocess
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: better multiprocessing and multithreading in python
  dev_url: http://github.com/uqfoundation/multiprocess

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
