# The language in this case has no bearing - we are going to be making use of conda.
language: generic

os: osx

# Set BINSTAR_TOKEN
env:
    global:
        secure: "RvoIhw++fN6fCKiczPCRpyNQojKDZhtZNHNqX741ez7jwU9GtGoDz4UrifhxwN1neeRvYxgA1Ra55IzamR+g+9qSKcv0l1pWTFYo+nR2AmNB3xj2UVYacpjVYpLfZNBS0y6GCv5+nro9aicqRQLuTSF343qte9P/ntGXLIbbWFazV/7oY9/HAhD/IJODXfZtJfvQS0o1ZX6wJ/yTZthszXQH+jfJjmy/QV7DPUShtnta9ShzWhInlqlUsF1N4nIY6vFULFKh92o1DOoYuqrSKdNn+MwBRvrfggf5pQDGEOvOA5jNFSfaOr5J8jFNRfosqEeNyCpgmmSGWfpkGqLQlCNdUSzYKKaAMh8xV6ofn/3t2+3psvdKTSVi39+ClwisACLvca7Kq+3gxhZBWoOVBLTcKoYTkES3Qq8I9TkGPAkxyTYsVPyPxpSHWFNhAcD4hGdfhy0DSFJ2fd/2LTtPI7xYxgSj/1Q1uU/0Ydrqx+z10r1b5jd0r9Cse/N7ptfCaA3sBcFFBgZY8rIWMjSJFaT5kpffqMNmGCnHQ2jXpfc0VRz/pA+zwFW3jdS9Pgndr7g0Y83Ury8ZX9+eha96tzja0wNPqM/j1eNOBOtXzA5RW8UO+HPr5AsGqKAuko4+5y3ZUc5KM4RxxPrTFCvto7klEVf7d2Ky+2qqTyqIosk="

before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew

install:
    # Install Miniconda.
    - ./install_miniconda.sh

script:
    - source ~/miniconda/bin/activate root
    - conda build ./recipe
    # from https://github.com/conda-forge/conda-forge-build-setup-feedstock/blob/master/recipe/upload_or_check_non_existence.py
    - ./upload_or_check_non_existence ./recipe sebp --channel=main
