# The language in this case has no bearing - we are going to be making use of conda.
language: generic

os: osx

# Set BINSTAR_TOKEN
env:
    global:
        secure: "LEKWYqIH1JX7KZTa/9/xfMd42cDxrkyr8JO2fTb4eIslKAlxTTCFu/oD7dlGl8wTz+0dqlp4VDVxHfcO+jYwTdj0LfNS94YXsvv8ZMIbuUOUy835UEbjMqLkP7rGhRw5R+3Fem0sblGhMxN2DcYJ+3XUX4VIZjffevwAsS7rO3ehrY6vQ3VSeX+jPAymoHhkyGekhQFOSXdPntLSa//M2PhChFnl380FcziNne0H+qu6ga9R01AVtl6Du4xX9h0T4PLvPG0z465li+114GWdQyQ91xCfqCLycNtEfLcIkxTebr+APEoXbw81I4k7YKF+KgmdZ2mvzSlz/cdSLSv4H2tsMqzXYO/NrCptQRALMCJc2itVh+abfjXZkUlv+SICPnRYKB2KXTzTaymOpP4kuuWnTbTqoqTMdpZFQCiReKc4tRoLmX7v2ihcX3PeaJo3/r8deKgCfJItKdKvAewKO7DNobJiNuQMRynsyMWtsgxKRbf6BRGO4MHZulWLBI8XeoRS4jjBfeh8m6Z/A1aLTaGotfIEi/jZJaiwoLdAYUmxdDeBh05JxMwnHvqSplAXhNQ5FqoRgvNTAP1xVHo0iO/AzDB4TZ4P6CjoBLt/6QMWpij8SCJExgBBCugurVxha9a+nguHPyK5Aea+fx6BhgAzpzcz6tjgzauwljZX2W0="

before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew

install:
    # Install Miniconda.
    - ./install_miniconda.sh

script:
    - source ~/miniconda/bin/activate root
    - conda build ./recipe
    # from https://github.com/conda-forge/conda-forge-build-setup-feedstock/blob/master/recipe/upload_or_check_non_existence.py
    - ./upload_or_check_non_existence ./recipe sebp --channel=main
